# -*- coding: utf-8 -*-
DEBUG = False
TESTING = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'lol'

WTF_CSRF_CHECK_DEFAULT = False

LOGIN_DISABLED = True
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False

USER_CABINET_PAGINATION_PER_PAGE = 50
COMMENTS_PER_CHUNK = 100
INITIAL_SUGGESTIONS_NUMBER = 50
SUGGESTIONS_PER_QUERY = 50
